campaign_lenght = int(input())
cooks_count = int(input())
cakes_count = int(input())
waffles_count = int(input())
pancakes_count = int(input())
cake_price = float(45)
waffle_price = float(5.80)
pancake_price = float(3.2)
total_cake_gain = float(campaign_lenght * cooks_count * cakes_count * cake_price)
total_waffle_gain = float(campaign_lenght * cooks_count * waffles_count * waffle_price)
total_pancakes_gain = float(campaign_lenght * cooks_count * pancakes_count * pancake_price)
total_gain = float(total_cake_gain + total_waffle_gain + total_pancakes_gain)
net_win = float(total_gain - 1/8 * total_gain)
print(net_win)